### PR TITLE
get rid of google redirect links

### PR DESCRIPTION
**Pull request by cyan-2048**
amazing work Ivan-HC! the migration from google sites was a great touch, however there are still redirect links that go to google's servers... it is somewhat annoying
image

I have made a script that fixes the <a> elements to not use google's redirect
image

If you have any distrust regarding the changes to the html files, you are free to undo the latest commit and run the script yourself, it is written in [bun](//bun.sh)
`bun i`
`bun cleanup.ts`

### CODE REVIEW

**Comment by ivan-hc** [comment]
Thank you for this effort, this site needed it.

**Comment by ivan-hc** [comment]
@cyan-2048 it seems that something is gone wrong https://github.com/ivan-hc/bananahackers/actions can you confirm?

**Comment by cyan-2048** [comment]
> @cyan-2048 it seems that something is gone wrong https://github.com/ivan-hc/bananahackers/actions can you confirm?

there is indeed an error, might be a random error that happened in github's servers, try re-running the github action.

**Comment by cyan-2048** [comment]
if there is no option to re-run the github pages action, i suggest changing one file to trigger the github pages deployment.

**Comment by ivan-hc** [comment]
I'm no more involved in the BananaHackers things... but this change had to be made sooner or later. I was very selfish at the beginning when this cleaning was proposed to me.

Thank you very much for this, @cyan-2048

**Pull request merged**
